# Generated by Django 4.2.14 on 2024-07-16 05:29

from django.db import migrations
from wordle_api.wordList import words

def seed_data(apps, schema_editor):
    MyModel = apps.get_model('wordle_api', 'Word')
    for word in words:
        MyModel.objects.create(word=word)

class Migration(migrations.Migration):

    dependencies = [
        ('wordle_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
